### ISSUE TITLE
Support null/empty values

### ISSUE THREAD

**Issue by slhck** [levibostian/dotenv-android#22]
This is a feature request.

When I add empty env variables like:

```
ELASTICSEARCH_TEST_URL=
```

Or:

```
ELASTICSEARCH_TEST_URL=""
```

These are not resolved, and therefore not available in the program code.

Feature: Make empty variables available in `Env`, but simply set to an empty string (in case of `""`), or `null` (in case of no value) so that you can programmatically deal with them and determine absence of the values.

Otherwise I have no easy way to provide optional values.

Consider the case where this `.env` file is necessary for a certain functionality only, so the values don't have to be set at all times. I cannot just remove them completely, as the code wouldn't compile anymore. I also cannot set them to bogus values like `foo`, because I would have to provide extra check like `if Env.elasticsearchTestUrl == "foo"` instead of a semantically more correct `if Env.elasticsearchTestUrl == null`, or add a check for `.length() == 0`.

**Comment by slhck** [comment]
Oh, I realize this should be added to https://github.com/levibostian/dotenv/ and not here. Moving there.

**Comment by levibostian** [comment]
The work to support this feature has been completed on the [CLI end](https://github.com/levibostian/dotenv/issues/9). Now, all that needs to happen is [update the CLI version in the plugin](https://github.com/levibostian/dotenv-android/pull/25) and this will ship!

**Comment by levibostian** [comment]
Deployed with v1.3.0 

https://github.com/levibostian/dotenv-android/releases/tag/1.3.0

**Comment by slhck** [comment]
This works perfectly now for my use case. Thank you!
