### ISSUE TITLE
Android Artifact Location

### ISSUE THREAD

**Issue by jayjacksonworks** [levibostian/dotenv-android#26]
Android Artifact Issue

Hey @levibostian , we just started to get some build errors due to this library artifact being hosted on BinTray/JCenter, which was shutdown. Is there another location we can pull from OR is there a plan to re-publish the artifacts somewhere else? 

https://docs.microsoft.com/en-us/appcenter/build/android/jcentershut

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve earth.levi:dotenv:1.2.0.
     Required by:
         project :
      > Could not resolve earth.levi:dotenv:1.2.0.
         > Could not get resource 'https://jcenter.bintray.com/earth/levi/dotenv/1.2.0/dotenv-1.2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/earth/levi/dotenv/1.2.0/dotenv-1.2.0.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by levibostian** [comment]
Hey there @jayjacksonworks. Thanks for asking. 

This project is not hosted on JCenter. It's hosted in the [Gradle Plugin repository](https://plugins.gradle.org/plugin/earth.levi.dotenv-android). Follow [these instructions](https://plugins.gradle.org/plugin/earth.levi.dotenv-android) to see if you can successfully pull down the plugin.
